Minimize type parameters
kelloggm/specimin pull request #103
Opened 2024-02-05 04:35 UTC by LoiNguyenCS

Professor,

This is the PR to remove unused type bounds of type parameters in the declaration of a class. After this PR and #101 are merged, Specimin will be able to minimize [AnalysisResult.java](https://github.com/mernst/checker-framework/blob/master/dataflow/src/main/java/org/checkerframework/dataflow/analysis/AnalysisResult.java).

2024-02-05 15:25 UTC, kelloggm requested changes

2024-02-05 15:25 UTC, kelloggm commented on src/test/java/org/checkerframework/specimin/UnusedTypeParameterBoundTest.java
> + * class.
Can you please add a test for generic type bounds that should not be removed, as well. We don't currently have one.

2024-02-05 15:25 UTC, kelloggm commented on src/test/java/org/checkerframework/specimin/UnusedTypeParameterBoundTest.java
> + * class.
(to check that, I searched our `src/test/resources/` directory for "extends", and then observed that none of the results are type variables)

2024-02-05 23:20 UTC, LoiNguyenCS commented
Professor,

I have updated the test case to remove one generic type bound and preserve the other type bound.

2024-02-06 14:17 UTC, kelloggm approved these changes
Thanks for the new test case. LGTM!

2024-02-06 14:17 UTC, merged