Add Exception
kelloggm/specimin pull request #145
Opened 2024-02-22 02:21 UTC by LoiNguyenCS

Professor,

This is one of the bug I've figured out while looking at the `CheckerFramework `issue.

I think the comment is clear enough to discourage future maintainers from removing this additional catch, so I did not add a test case.

2024-02-22 17:39 UTC, kelloggm requested changes
I'd strongly prefer that we add a test case. If you're unwilling to write one for some reason, please let me know why; I think this PR _could_ be merged without one, but doing so makes me nervous (since this is supposed to fix a crash, no?).

2024-02-22 20:14 UTC, LoiNguyenCS commented
Professor,

I will add a test case. But at the moment this PR is not ready to be merged, the reason is that I am still not sure what to do if resolving a type ends up in an `IlegalAgrumentException`.

2024-02-23 03:15 UTC, LoiNguyenCS commented
Upon further investigation, I have realized that this is a bug of Specimin rather than a false exception of JavaParser.

The bug happens because for some unsolved types with type variables, Specimin create synthetic versions of them with no type variables.

2024-02-26 01:56 UTC, LoiNguyenCS commented
Closing this PR in favor of #146.

2024-02-26 01:56 UTC, closed without merging