Fix bugs with array type
kelloggm/specimin pull request #39
Opened 2023-11-11 03:39 UTC by LoiNguyenCS

2023-11-11 03:49 UTC, LoiNguyenCS commented
Professor,

This is the PR to fix the issue #37 that Jonathan has. I'm not sure if this is a minor bug of JavaParser or not. This is the code snippet where we get the bug:

```
  Type returnType = method.getType();
   if (returnType instanceof ReferenceType) {
        usedClass.add(returnType.resolve().asReferenceType().getQualifiedName());
   }
```

The problem arises when `returnType` is an array type. In such cases, JavaParser incorrectly considers it as a reference type, leading to a bug when trying to resolve and cast it.

The solution is to resolve `returnType` first before checking if it is an instance of reference type.

2023-11-13 14:22 UTC, kelloggm requested changes

2023-11-13 14:22 UTC, kelloggm commented on src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java
> +      if (returnType.resolve() instanceof ResolvedReferenceType) {
Please add a comment here explaining that this is working around a JavaParser bug. (The comment should explain exactly what you explained in the comment you opened on this PR.)

2023-11-13 14:23 UTC, kelloggm commented
> I'm not sure if this is a minor bug of JavaParser or not

I'd call this a bug in JavaParser. Unfortunately, we have to work around it here.

2023-11-13 18:17 UTC, kelloggm approved these changes

2023-11-13 18:17 UTC, merged