Codes and tests for tricky anonymous class field
kelloggm/specimin pull request #74
Opened 2023-12-09 07:01 UTC by LoiNguyenCS

Professor,

This is the PR to fix #73. I have replace the field `insideAnObjectCreation` with a method with the same name. I have also changed the way we get the simple name of a type (previously we used the `asString` method, which is not very accurate when there is a special symbol going with the type, such as [] or <>). And I have added codes to remove every class declaration that is not used by the target methods.

2023-12-11 16:56 UTC, kelloggm requested changes
This PR appears to contain code that is unrelated to fixing #73. Can you separate that code (i.e., the changes to how type variables are handled) into its own PR with its own test case? Once that is done, I can review this PR properly.

2023-12-22 21:23 UTC, LoiNguyenCS commented
Professor,
I have removed the unrelated components. Please take a look. Thank you.

2024-01-03 20:39 UTC, kelloggm commented on src/test/resources/ObjectCreationInsideAnonymousClass/expected/com/example/Simple.java
> +            private Foo foo;
The initializer of this field is part of the target method `getBaz()`, so I wouldn't expect it to be removed here.

2024-01-22 19:52 UTC, LoiNguyenCS commented
Professor,

I have updated the codes. Please take a look. Thank you.

2024-01-22 20:43 UTC, kelloggm approved these changes
One minor comment, but I don't need to review this again once that is fixed.

2024-01-22 20:43 UTC, kelloggm commented on src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java
> +      usedClass.add(method.resolve().getPackageName() + "." + method.resolve().getClassName());
The code both here and on line 198 calls `method.resolve()` twice. This call is relatively expensive (it invokes the symbol solver), so we should call it once and store the result in a local variable.

2024-01-22 20:57 UTC, merged